### ISSUE TITLE
PHP-IMDb-Scraper Error

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#1]
not fetching

image
genres
run time
release date
actors
rating 
And etc

**Comment by lyarinet** [comment]
Sir solve this please

**Comment by lyarinet** [comment]
Title 			working
Runtime 		        notworking
Release Date 	        notworking
Picture			notworking
Storyline		        notworking
Cast			        notworking
MPAA_RATING	notworking
Rating 			notworking
Genres			notworking

**Comment by maknol** [comment]
iMDB removed the page combined, ths is the reason for not working.
For now you can use this one - https://github.com/FabianBeiner/PHP-IMDB-Grabber/issues/87

In the comment from  **paulitap**

**Comment by dhobi** [comment]
I hope the referenced commit fixes this.
