### ISSUE TITLE
Cast, Character to Real Name

### ISSUE THREAD

**Issue by pemtorrent** [dhobi/PHP-IMDb-Scraper#10]
Hello, that not issue more wiki, 
how to make show Actors real name instead Character
simple explanation and I think many peaple will be interested by what I had seen in previous issues.

`$arr['cast'] = $this->match_all_key_value('/itemprop="name">(.*?)<.*?<td class="character">.*?<div>(.*?)<\/div>/ms', $this->match('/<table class="cast_list">(.*?)<\/table>/ms', $html, 1));`

and COUNTRY, LANGUAGE, VIDEOS empty

**Comment by dhobi** [comment]
Country, language and videos should be fixed now.

About cast: it contains both, the real name and the character name as key/value pairs where key is the real name and the value is the movie character name. 

Example output from The Avengers:
`"CAST":{"Robert Downey Jr.":"Tony Stark \/ Iron Man","Chris Evans":"Steve Rogers \/ Captain America", ...`
Which means:
Robert Downey Jr. plays Tony Stark / Iron Man
Chris Evans plays Steve Rogers / Captain America

**Comment by dhobi** [comment]
I'm closing this issue now. Please reopen if you think different about this topic.
