### ISSUE TITLE
imdb change image link

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#13]
imdb change image link fix it please

**Comment by maknol** [comment]
Try changing:
`$arr['poster'] = $this->match('/class="titlereference-primary-image".*?src="(.*?)".*? \/>/ms', $html, 1);`

with:
`$arr['poster'] = $this->match('/<meta\s*property=\'og:image\'\s*content="(.*?)" \/>/ms', $html, 1);`

**Comment by lyarinet** [comment]
change this line image not get working
$arr['poster'] = $this->match('/<meta\s*property=\'og:image\'\s*content="(.*?)" \/>/ms', $html, 1);

**Comment by Jenkler** [comment]
I have tried the patches but non are working. Does anyone here have a working patch for image fetching?

**Comment by dhobi** [comment]
The matcher was still valid. It was just that the DNS name for the image has changed. Hope the lastest commit fixes this for you.

**Comment by Jenkler** [comment]
Updated the code, works now! Thanks :)

**Comment by lyarinet** [comment]
thanks
