### ISSUE TITLE
Not Working From Today

### ISSUE THREAD

**Issue by thetonmoyroy** [dhobi/PHP-IMDb-Scraper#14]
Unable To Scrape IMDB :""(

**Comment by maknol** [comment]
Yes, not working, again changes...

**Comment by tonuroy336** [comment]
is any one able to fix this

**Comment by thetonmoyroy** [comment]
Thankyou Sir For Replay Please Fix This .If Possible

**Comment by dhobi** [comment]
I hope the commit fixes this. Reopen if this is not the case.

**Comment by thetonmoyroy** [comment]
Sir Still Not Working For Me .My Website Uses Search Method Title Already Stored In Database  .Every was Fine now its not working .i attached my php files plz take a look

[fetch_imdb.php.log](https://github.com/dhobi/PHP-IMDb-Scraper/files/1923927/fetch_imdb.php.log)
[imdb.php.log](https://github.com/dhobi/PHP-IMDb-Scraper/files/1923928/imdb.php.log)

**Comment by thetonmoyroy** [comment]
not working with your index.php too .shows No Title Found Imdb.not working. plz

**Comment by dhobi** [comment]
Which title / id?

**Comment by thetonmoyroy** [comment]
all title .eg. Iron Man 3 .i tested recent imdb scraper commit with your index .php not workin but on ur demo site its works . please sir 

![capture](https://user-images.githubusercontent.com/38457260/38949991-f43209f6-4365-11e8-8433-b7553a35bf38.PNG)
![capture2](https://user-images.githubusercontent.com/38457260/38949988-f39c2a26-4365-11e8-9d0d-7d33ba4fb9d6.PNG)

![my site](https://user-images.githubusercontent.com/38457260/38949990-f3eba542-4365-11e8-8152-89d5cf377d3e.PNG)

Please Sir Help Me

**Comment by thetonmoyroy** [comment]
Sir I Have Checked Every Thing .Script Not Working From Local Host .But Works On Cloud Hosting .Both Cloud And Local Server Php And Apache Version Same

**Comment by dhobi** [comment]
Could be that your localhost environment has no trusted root certificates available for php curl. Try to add the following line to the geturl($url) function:
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false)

**Comment by thetonmoyroy** [comment]
Thank You Sir Now Its Working Perfectly 🥇 
But Too Slow

**Comment by dhobi** [comment]
I don‘t see much performance improvement potential here since I think the slowest is the fetching of the urls. Forking processes to fetch urls in parallel would be a possibility but I won‘t do it ;-)

**Comment by thetonmoyroy** [comment]
Thank You Very Much For Giving Your Valuable Time .Thank You Sir .
