### ISSUE TITLE
ones again imdb title not search  

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#15]
ones again imdb title not search 

{"ERROR":"No Title found on IMDb!"}

**Comment by lyarinet** [comment]
i solve this

change line 
href="http:\/\/www.imdb.com\/title\/(tt\d+)\/reference" \/>/ms'
to
href="https:\/\/www.imdb.com\/title\/(tt\d+)\/reference" \/>/ms'

**Comment by dhobi** [comment]
I already did this in #14 ...

**Comment by maknol** [comment]
No, it's not chaneged, i just make that too.

**Comment by maknol** [comment]
I chaneged all HTTP to HTTPS and now working

**Comment by dhobi** [comment]
Yes, I will change the other (http) occurrences soon as well. Thanks!

**Comment by lyarinet** [comment]
Thanks to replay sir

**Comment by dhobi** [comment]
I hope the commit fixes this. Reopen if this is not the case.
