### ISSUE TITLE
No poster url is fetched

### ISSUE THREAD

**Issue by Jenkler** [dhobi/PHP-IMDb-Scraper#16]
Using code from 18 april 2018 and it does not work. Maybe they changed the url or something. It would be nice if you could check this out.

Thanks :)

**Comment by maknol** [comment]
Yes, they changed something :(

**Comment by dhobi** [comment]
aec00bd should fix this poster issue. Reopen if this is not the case for you.

**Comment by Jenkler** [comment]
Now it works as it should, thanks man!
