### ISSUE TITLE
Searching From Google Not Working 

### ISSUE THREAD

**Issue by thetonmoyroy** [dhobi/PHP-IMDb-Scraper#17]
Title Search On Google Not Working .It Uses Bing For Search
 Bing Showing Inaccurate Result  
Example

Game Of Thrones Fire And Blood 

not found

**Comment by thetonmoyroy** [comment]
Maybe Google Regex Not Matching

**Comment by dhobi** [comment]
I'm unable to reproduce this. Works for me™ just fine...

**Comment by dhobi** [comment]
Closed (reopen if the issue still exists for you)
