### ISSUE TITLE
Title is showing original title

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#19]
Title is showing original title
"TITLE_ID": "tt0106544",
"IMDB_URL": "https://www.imdb.com/title/tt0106544/",
"TITLE": "Chiu kup gai wak",
"ORIGINAL_TITLE": **"",**

**Comment by lyarinet** [comment]
wating

**Comment by dhobi** [comment]
https://github.com/dhobi/PHP-IMDb-Scraper/commit/c0a7a2c5c6e34282ca02c56561d5ea7ab7c09392 should fix this issue
