### ISSUE TITLE
Your demo page shows 'false' for the 'VOTES' field. I expected a number, >= 0

### ISSUE THREAD

**Issue by pbb-xx** [dhobi/PHP-IMDb-Scraper#2]
I have been using Abhinay's original script for quite a while, but he seems to have given up back in 2014.

Is the votes thing an issue?

How easy would it be to replace Abhinay's script with yours?

**Comment by dhobi** [comment]
Yes, the votes thing was an issue and should be fixed now.
Since the "output structure" is exactly the same as in Abhinay's script you should be able to drop-in replace the imdb.php file.
