### ISSUE TITLE
Cast also showing movie character name

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#6]
stars working fine but 
Cast also showing movie character name

**Comment by dhobi** [comment]
Yes, this is (was) by design. 
It's basically an object with key:value pairs where key=real name and value=movie character name.

Let me know if you think different. I added the wontfix label and close the issue for now.

**Comment by lyarinet** [comment]
ok stars show only 3 name i want 10 name how to do
