### ISSUE TITLE
stars showing only 3 name

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#7]
stars show only 3 name how to do more then 5 name show

**Comment by dhobi** [comment]
Could you provide a movie imdb id and tell me what output you expect?

**Comment by lyarinet** [comment]
id is tt5956100 
and stars show only 3 actors name

**Comment by conyum** [comment]
There is only 3 names visible on imdb under stars so that's not anything weird at all

**Comment by dhobi** [comment]
Ok, thx for the info @conyum. Issue closed for me.
