### ISSUE TITLE
$arr['stars'] = array_slice($arr['cast'], 0, 5);

### ISSUE THREAD

**Issue by lyarinet** [dhobi/PHP-IMDb-Scraper#8]
still not working it's show 3 stars

wen i change it  like 
$arr['stars'] = array_slice($arr['cast'], 0, 5);
$arr['stars'] = array_slice($arr['cast'], 0, 10);
then it's show movie character name

**Comment by lyarinet** [comment]
sorry it's ok my mistake it's work perfect

Thanks Dear

**Comment by dhobi** [comment]
Ok, no problem. Closed.
